import { BiSolidMedal } from "react-icons/bi";
import { BsGraphUpArrow } from "react-icons/bs";
import { FaHandsHoldingCircle } from "react-icons/fa6";
import { ImUserTie } from "react-icons/im";

export const AcademicPostData = [
  {
    id: 1,
    icon: BiSolidMedal,
    title: `23 Years`,
    desc: `of Excellence In Education`,
    subDesc1: `Comprehensive curriculum aligned with industry standards.`,
    subDesc2: `Expert faculty with real-world hospitality experience.`,
    subDesc3: `Hands-on training in modern hotel management practices.`,
    subDesc4: `State-of-the-art facilities for practical learning.`,
    subDesc5: `Strong focus on leadership and communication skills.`,
    subDesc6: `Internship opportunities with top hospitality brands.`,
    img: `/Images/8.jpg`,
    boxclass: ``,
    imgclass: ``,
    innerclass: `border-r-[1px] border-b-[1px] bg-[#3e3e8e] border-[white]`,
  },
  {
    id: 2,
    icon: ImUserTie,
    title: `Jobs & Internships`,
    desc: `With Top International Brands & MNC's`,
    subDesc1: `Unlock Prestigious Jobs with VIMS Connections.`,
    subDesc2: `Launch Your Career with VIMS Placements.`,
    subDesc3: `Secure Internships at Leading Brands with VIMS.`,
    subDesc4: `Opening Doors to Careers through VIMS.`,
    subDesc5: `VIMS Internship Programs for Career Advancement.`,
    subDesc6: `Connect with Industry Leaders through VIMS Opportunities.`,
    img: `/Images/About/2.jpg`,
    boxclass: `order-2`,
    imgclass: `max-xl:order-2`,
    innerclass: `border-l-[1px] border-b-[1px] bg-[#3e3e8e] border-[white]`,
  },
  {
    id: 3,
    icon: FaHandsHoldingCircle,
    title: `Daily Practical`,
    desc: `in a professional environment`,
    subDesc1: `Master Skills with Daily Practical Sessions at VIMS.`,
    subDesc2: `Hands-On Learning Through Daily Practical Training.`,
    subDesc3: `Elevate Your Expertise with Daily Practicals.`,
    subDesc4: `Sharpen Skills Daily with VIMS Practical Programs.`,
    subDesc5: `Practical Learning Every Day for Real-World Success.`,
    subDesc6: `Daily Hands-On Training for Future Professionals.`,
    img: `/Images/About/1.jpg`,
    boxclass: ``,
    imgclass: ``,
    innerclass: `border-r-[1px] border-b-[1px] bg-[#3e3e8e] border-[white]`,
  },
  {
    id: 4,
    icon: BsGraphUpArrow,
    title: `97.2% Placement`,
    desc: `record (IT & JT)`,
    subDesc1: `Exceptional Career Outcomes for VIMS Graduates.`,
    subDesc2: `Securing Top Jobs for Almost Every Graduate.`,
    subDesc3: `Launch Your Career with Outstanding Placement Support.`,
    subDesc4: `Graduates Achieve Career Success with High Placement Rates.`,
    subDesc5: `Unlock Career Success with Our Proven Placement Record.`,
    subDesc6: `Join the Majority of VIMS Graduates in Top Careers.`,
    img: `/Images/6.jpg`,
    boxclass: `order-2`,
    imgclass: `max-xl:order-2`,
    innerclass: `border-l-[1px] border-b-[1px] bg-[#3e3e8e] border-[white]`,
  },
];
